import QtQuick

Item {
    property var currencyCodes:[
        qsTr("AED"),
        qsTr("ARS"),
        qsTr("AUD"),
        qsTr("BCH"),
        qsTr("BDT"),
        qsTr("BHD"),
        qsTr("BRL"),
        qsTr("BTC"),
        qsTr("CAD"),
        qsTr("CHF"),
        qsTr("CLP"),
        qsTr("CNY"),
        qsTr("CZK"),
        qsTr("DKK"),
        qsTr("ETH"),
        qsTr("EUR"),
        qsTr("GBP"),
        qsTr("GEL"),
        qsTr("HKD"),
        qsTr("HUF"),
        qsTr("IDR"),
        qsTr("ILS"),
        qsTr("INR"),
        qsTr("JPY"),
        qsTr("KRW"),
        qsTr("KWD"),
        qsTr("LTC"),
        qsTr("LKR"),
        qsTr("MMK"),
        qsTr("MXN"),
        qsTr("MYR"),
        qsTr("NGN"),
        qsTr("NOK"),
        qsTr("NZD"),
        qsTr("PHP"),
        qsTr("PKR"),
        qsTr("PLN"),
        qsTr("RUB"),
        qsTr("SAR"),
        qsTr("SEK"),
        qsTr("SGD"),
        qsTr("THB"),
        qsTr("TRY"),
        qsTr("TWD"),
        qsTr("USD"),
        qsTr("UAH"),
        qsTr("VEF"),
        qsTr("VND"),
        qsTr("XAG"),
        qsTr("XAU"),
        qsTr("ZAR"),
    ]

    property var currencyNames:[
        qsTr("United Arab Emirates Dirham"),
        qsTr("Argentine Peso"),
        qsTr("Australian Dollar"),
        qsTr("Bitcoin Cash"),
        qsTr("Bangladeshi Taka"),
        qsTr("Bahraini Dinar"),
        qsTr("Brazilian Real"),
        qsTr("Bitcoin"),
        qsTr("Canadian Dollar"),
        qsTr("Swiss Franc"),
        qsTr("Chilean Peso"),
        qsTr("Chinese Yuan"),
        qsTr("Czech Koruna"),
        qsTr("Danish Krone"),
        qsTr("Ethereum"),
        qsTr("Euro"),
        qsTr("British Pound Sterling"),
        qsTr("Georgian Lari"),
        qsTr("Hong Kong Dollar"),
        qsTr("Hungarian Forint"),
        qsTr("Indonesian Rupiah"),
        qsTr("Israeli New Shekel"),
        qsTr("Indian Rupee"),
        qsTr("Japanese Yen"),
        qsTr("South Korean Won"),
        qsTr("Kuwaiti Dinar"),
        qsTr("Litecoin"),
        qsTr("Sri Lankan Rupee"),
        qsTr("Myanmar Kyat"),
        qsTr("Mexican Peso"),
        qsTr("Malaysian Ringgit"),
        qsTr("Nigerian Naira"),
        qsTr("Norwegian Krone"),
        qsTr("New Zealand Dollar"),
        qsTr("Philippine Peso"),
        qsTr("Pakistani Rupee"),
        qsTr("Polish Zloty"),
        qsTr("Russian Ruble"),
        qsTr("Saudi Riyal"),
        qsTr("Swedish Krona"),
        qsTr("Singapore Dollar"),
        qsTr("Thai Baht"),
        qsTr("Turkish Lira"),
        qsTr("New Taiwan Dollar"),
        qsTr("United States Dollar"),
        qsTr("Ukrainian Hryvnia"),
        qsTr("Venezuelan Bolívar"),
        qsTr("Vietnamese Dong"),
        qsTr("Silver Ounce"),
        qsTr("Gold Ounce"),
        qsTr("South African Rand"),
    ]

    property var currencySymbols:[
        "د.إ",
        "$",
        "$",
        "BCH",
        "Tk",
        "BD",
        "R$",
        "₿",
        "$",
        "SFr",
        "$",
        "¥",
        "Kč",
        "kr",
        "Ξ",
        "€",
        "£",
        "₾",
        "$",
        "Ft",
        "Rp",
        "₪",
        "₹",
        "¥",
        "₩",
        "د.ك",
        "Ł",
        "Rs",
        "K",
        "$",
        "RM",
        "₦",
        "kr",
        "$",
        "₱",
        "Rs",
        "zł",
        "₽",
        "ر.س",
        "kr",
        "$",
        "฿",
        "₺",
        "NT$",
        "$",
        "₴",
        "Bs.",
        "₫",
        "XAG",
        "XAU",
        "R",
    ]

}
